# Generated by Django 6.0.2 on 2026-03-15 06:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'default_related_name': 'business_types',
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'default_related_name': 'lead_sources',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CALLED', 'Called'), ('FOLLOW_UP', 'Follow Up'), ('INTERESTED', 'Interested'), ('PROPOSAL_SENT', 'Proposal Sent'), ('WON', 'Won'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=30)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('priority_score', models.IntegerField(db_index=True, default=0)),
                ('is_vip', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('google_maps_url', models.URLField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('business_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.businesstype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadsource')),
            ],
            options={
                'default_related_name': 'leads',
            },
        ),
        migrations.AddIndex(
            model_name='businesstype',
            index=models.Index(fields=['organization'], name='leads_busin_organiz_926e77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businesstype',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['organization'], name='leads_leads_organiz_20d99c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leadsource',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization'], name='leads_lead_organiz_fbd209_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='leads_lead_assigne_3f8857_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'status'], name='leads_lead_organiz_1ed3c6_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'assigned_to'], name='leads_lead_organiz_015109_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'created_at'], name='leads_lead_organiz_cb2e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='leads_lead_organiz_b0811b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'assigned_to', 'status'], name='leads_lead_organiz_e614ae_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'status', 'assigned_to'], name='leads_lead_organiz_860a4f_idx'),
        ),
    ]
