# Generated by Django 6.0.2 on 2026-03-15 06:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('entity_type', models.CharField(choices=[('ACTIVITY', 'Activity'), ('LEAD', 'Lead'), ('DEAL', 'Deal'), ('USER', 'User')], db_index=True, max_length=50)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'default_related_name': 'audit_logs',
            },
        ),
    ]
