# Generated by Django 6.0.2 on 2026-03-05 22:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('affects_pipeline', models.BooleanField(default=False)),
                ('pipeline_status', models.CharField(blank=True, choices=[('NEW', 'New'), ('CALLED', 'Called'), ('FOLLOW_UP', 'Follow Up'), ('INTERESTED', 'Interested'), ('PROPOSAL_SENT', 'Proposal Sent'), ('WON', 'Won'), ('LOST', 'Lost')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_types', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('next_follow_up', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('activity_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activitytype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activitytype',
            index=models.Index(fields=['organization'], name='activities__organiz_b55945_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activitytype',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['organization'], name='activities__organiz_b78fee_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['lead'], name='activities__lead_id_48f544_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['next_follow_up'], name='activities__next_fo_fd79a7_idx'),
        ),
    ]
