# Generated by Django 6.0.2 on 2026-03-05 22:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(help_text='Pipeline order')),
                ('is_closed', models.BooleanField(default=False, help_text='Stage closes the deal')),
                ('is_won', models.BooleanField(default=False, help_text='Marks deal as won')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_stages', to='accounts.organization')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='leads.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='accounts.organization')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='deals.dealstage')),
            ],
        ),
        migrations.AddIndex(
            model_name='dealstage',
            index=models.Index(fields=['organization'], name='deals_deals_organiz_102ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='dealstage',
            index=models.Index(fields=['organization', 'order'], name='deals_deals_organiz_ee6e01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dealstage',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization'], name='deals_deal_organiz_6d9c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'stage'], name='deals_deal_organiz_293389_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'closed_at'], name='deals_deal_organiz_8e874d_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'value'], name='deals_deal_organiz_9f6c73_idx'),
        ),
    ]
