class EventTypes:
    LEAD_CREATED = 'LEAD_CREATED'
    ACTIVITY_CREATED = 'ACTIVITY_CREATED'

    DEAL_STAGE_CHANGED = 'DEAL_STAGE_CHANGED'
    DEAL_CREATED = 'DEAL_CREATED'
    DEAL_REOPENED = 'DEAL_REOPENED'
    DEAL_WON = 'DEAL_WON'
    DEAL_LOST = 'DEAL_LOST'



