class EventTypes:
    # Audit events
    LEAD_CREATED = 'LEAD_CREATED'
    ACTIVITY_CREATED = 'ACTIVITY_CREATED'

    DEAL_STAGE_CHANGED = 'DEAL_STAGE_CHANGED'
    DEAL_CREATED = 'DEAL_CREATED'
    DEAL_REOPENED = 'DEAL_REOPENED'
    DEAL_WON = 'DEAL_WON'
    DEAL_LOST = 'DEAL_LOST'

    # Task events
    TASK_CREATED = "TASK_CREATED"
    TASK_COMPLETED = "TASK_COMPLETED"

    # Reminder events
    REMINDER_TRIGGERED = "REMINDER_TRIGGERED"

    # Notification events
    NOTIFICATION_CREATED = "NOTIFICATION_CREATED"

    # Note events
    NOTE_CREATED = "NOTE_CREATED"

